### ISSUE TITLE
Cursor not showing 

### ISSUE THREAD

**Issue by Sulcalibur** [olmokramer/atom-block-cursor#20]
Cursor not shown at all. No block, line or anything.

Currently using Atom Version 0.209.0 (0.209.0)

**Comment by olmokramer** [comment]
Yeah, this is an issue with the new tile rendering of the editor... You can use the `cursorLineFix` config as a workaround for now, but it is not a perfect solution. You'll have to use very low alpha, because it renders the cursor above the text.

Not much more I can do about this right now, I'm afraid. I'll talk with the Atom team, and see if this can be fixed somehow...

**Comment by olmokramer** [comment]
Hey, I've just published a new version that should work around this problem as I described above. It breaks the current configuration, so you will need to set it up again.

**Comment by Sulcalibur** [comment]
Superb, many thanks!
