### ISSUE TITLE
None blinking block cursor with opacity 100%

### ISSUE THREAD

**Issue by cyangle** [olmokramer/atom-block-cursor#39]
![block-cursor](https://user-images.githubusercontent.com/15083254/32255715-464b45cc-be78-11e7-9ed7-9df7aa80f7dc.png)
This screen shot is from visual studio code. It has a configuration setting for block cursor.
And the opacity is 100%, it's black on white. You can also change the cursor colour.
Well, VSC is also using electron so I think this is possible for atom too.
Currently I'm using VSC instead of atom because of this.

**Comment by adamrenklint** [comment]
This is unfortunately hard to implement, because all the cursors exist in a layer separate from the text in the editor, so we cannot simply say that the character under the cursor should change color. 

I made an experiment that hooks up a listener to `editor.onDidChangeCursorPosition`, finds the character at the cursor and adds a coloured marker where the cursor should be. Works visually, but it's very slow to work on boot, and affects performance when you have multiple cursors and have to redraw all markers on each cursor movement.

If anyone has an idea for an other implementation, given the constraints of Atom's editor architecture, I'd be happy to discuss that. Until then, this is simply not something we can solve.
