### ISSUE TITLE
cursor type option is missing

### ISSUE THREAD

**Issue by despairblue** [olmokramer/atom-block-cursor#8]
The option dropdown menu for choosing the cursor type is missing since 11.1 (or maybe 11.0 already). This is probably just a minor glitch that happened while moving to scoped config.

**Comment by olmokramer** [comment]
I think I know what causes this. I had to change the values of that select box for scoped config support, but I forgot to communicate that. I think this can be fixed by removing the setting from your `config.cson`, then reload Atom, then select the cursor type you want. I'm sorry for the inconvenience.

Please let me know if this works, or wait a few minutes for a new version that converts the old value to the new value automatically. Thanks for bringing this up!

**Comment by despairblue** [comment]
Thanks for replying so quickly :)

Sadly no: 
![screenshot 2015-03-29 16 21 02](https://cloud.githubusercontent.com/assets/927609/6886005/5dd9e830-d62f-11e4-9a2c-2a75b8d06bb4.png)

The drop down menu is just gone :/

**Comment by olmokramer** [comment]
I already found the problem, it's because I forgot to change the default value, and apparently Atom ignores a setting if it's default value isn't allowed. New version is up

**Comment by despairblue** [comment]
:tada: thx :smiley:

**Comment by olmokramer** [comment]
Glad to hear it works!
